### Copied from https://github.com/scikit-image/scikit-image/blob/main/.github/workflows/benchmarks.yml

name: Benchmark

on:
  pull_request_target:
    # types: [labeled, synchronize]

# permissions:
#   contents: read

jobs:
  ## This code below is to make sure a new commit on a PR with the label
  ## retriggers the benchmark, otherwise the label needs to be removed and
  ## applied again to run the benchmark.
  check:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check.outputs.result }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/github-script@v7
        name: Check for benchmark label and new commit
        id: check
        with:
          script: |
            const { owner, repo, number: pull_number } = context.issue;

            // Check for label
            const { data: pullRequest } = await github.rest.pulls.get({ owner, repo, pull_number });
            if (!pullRequest.labels.some(({ name }) => name === 'benchmark')) {
              return false;
            }

            // Check for repo name and organization name
            const { data: repository } = await github.rest.repos.get({ owner, repo });
            return repository.name === 'astropy' && repository.owner.login === 'astropy';

  benchmark:
    needs: check
    if: ${{ needs.check.outputs.result == 'true' }}
    name: "Compare asv with astropy main"
    runs-on: ubuntu-latest
    env:
      CCACHE_BASEDIR: "${{ github.workspace }}"
      CCACHE_DIR: "${{ github.workspace }}/.ccache"
      CCACHE_COMPRESS: true
      CCACHE_COMPRESSLEVEL: 6
      CCACHE_MAXSIZE: 400M

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: "3.11"

      - name: Setup some dependencies
        shell: bash -l {0}
        run: |
          sudo apt-get update -y && sudo apt-get install -y ccache
          # Make gcc/gxx symlinks first in path
          sudo /usr/sbin/update-ccache-symlinks
          echo "/usr/lib/ccache" >> $GITHUB_PATH

      - name: "Prepare ccache"
        id: prepare-ccache
        shell: bash -l {0}
        run: |
          echo "key=benchmark-$RUNNER_OS" >> $GITHUB_OUTPUT
          echo "timestamp=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT
          ccache -p
          ccache -z

      - name: "Restore ccache"
        uses: actions/cache@v3
        with:
          path: .ccache
          key: ccache-${{ secrets.CACHE_VERSION }}-${{ steps.prepare-ccache.outputs.key }}-${{ steps.prepare-ccache.outputs.timestamp }}
          restore-keys: |
            ccache-${{ secrets.CACHE_VERSION }}-${{ steps.prepare-ccache.outputs.key }}-

      - name: Run benchmarks
        shell: bash -l {0}
        id: benchmark
        env:
          OPENBLAS_NUM_THREADS: 1
          MKL_NUM_THREADS: 1
          OMP_NUM_THREADS: 1
          ASV_FACTOR: 1.5
          ASV_SKIP_SLOW: 1
        run: |
          set -x
          python -m pip install asv virtualenv packaging

          git clone -b main https://github.com/astropy/astropy-benchmarks.git --single-branch

          # ID this runner
          python -m asv machine --yes --conf asv.ci.conf.json

          echo "Baseline:  ${{ github.event.pull_request.base.sha }} (${{ github.event.pull_request.base.label }})"
          echo "Contender: ${GITHUB_SHA} (${{ github.event.pull_request.head.label }})"

          # Run benchmarks for current commit against base
          # ASV_OPTIONS="--split --show-stderr --factor $ASV_FACTOR --conf asv.ci.conf.json"
          # python -m asv continuous $ASV_OPTIONS ${{ github.event.pull_request.base.sha }} ${GITHUB_SHA} \
          #     | sed "/Traceback \|failed$\|PERFORMANCE DECREASED/ s/^/::error::/" \
          #     | tee benchmarks.log
          echo "Benchmarking complete." > benchmarks.log
          # # Report and export results for subsequent steps
          # if grep "Traceback \|failed\|PERFORMANCE DECREASED" benchmarks.log > /dev/null ; then
          #    exit 1
          # fi

      - name: "Check ccache performance"
        shell: bash -l {0}
        run: ccache -s
        # if: always()

      - uses: actions/upload-artifact@v4
        # if: always()
        with:
          name: asv-benchmark-results-${{ runner.os }}
          path: benchmarks.log

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: asv-benchmark-results-${{ runner.os }}

      - name: Read artifact
        id: artifact
        run: echo "content=$(cat asv-benchmark-results-${{ runner.os }}/benchmarks.log)" >> $GITHUB_OUTPUT

      - name: Create comment
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.payload.pull_request.number;
            const body = `
            <details>
              <summary>Benchmark results</summary>

              \`\`\`
              ${{ steps.artifact.outputs.content }}
              \`\`\`
            </details>
            `;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: body
            });
