name: Test run

on:
  workflow_dispatch:
  pull_request:
    # We also want this workflow triggered if the 'Extra CI' label is added
    # or present when PR is updated
    types:
      - synchronize
      - labeled
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Python 3.12
    if: (github.repository == 'mriduls/astropy' && (github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'Extra CI')))
    steps:
      - name: Test
        shell: bash
        run: |
          echo "test"
